### ISSUE TITLE
why are you putting in multiple listeners and login?`

### ISSUE THREAD

**Issue by Murky-MoMo** [Joey-web-e2/when-i-have-time-in-shcool#1]
well 
instead of 
```
client.on("message", message => {
    if(command == "command1") {...}
}) 
client.on("message", message => {
    if(command == "command2") {...}
}) 
```
you can put that all in one event listener
```
client.on("message", message => {
    if(command == "command1") {...}
    if(command == "command2") {...}
    /
}) 
``` 
or even use else ifs

multiple event listeners are bad because all of them will execute at that event, and if you add more than 11, you'll get a `MEMORY LEAK ERROR`
you'd only want one message event listener
in case you need a bit help on [if cases](https://javascript.info/ifelse)

**Comment by JosephE2** [comment]
thanks
